version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
  celery:
    build: .
    command: celery -A djangorediscelery beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    links:
      - db
      - redis
